name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Cpanel
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/u1605088/public_html/cosim.rumahilmu.org
            git pull origin main
            source /home/u1605088/virtualenv/public_html/cosim.rumahilmu.org/3.10/bin/activate && cd /home/u1605088/public_html/cosim.rumahilmu.org
            pip install -r requirements.txt
            touch tmp/restart.txt
